version: '3.8'

networks:
  tokomas:


services:
  app:
    build:
      context: .
      args:
        - UID=${LOCAL_UID:-1000}
        - GID=${LOCAL_GID:-1000}
    ports:
      - "7000:80"
      - "9000:9000"
    volumes:
      - .:/var/www/html:delegated
#    depends_on:
#      - database
    networks:
      - tokomas

#  database:
#    image: mariadb:10.6
#    restart: unless-stopped
#    tty: true
#    ports:
#      - 3306:3306
#    volumes:
#      - ./mysql:/var/lib/mysql
#    environment:
#      MYSQL_DATABASE: ${DB_DATABASE}
#      MYSQL_USER: ${DB_USERNAME}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#    networks:
#      - tokomas
